kind: Deployment
apiVersion: apps/v1
metadata:
  name: alpine-ovn
  labels:
    dce.daocloud.io/component: alpine-ovn
    dce.daocloud.io/app: crossx-ovn
  namespace: dev-env
  annotations: {}
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - securityContext:
            privileged: true
          name: alpine-ovn
          image: 'registry.cn-hangzhou.aliyuncs.com/sourcegarden/openvpn:alpine-v1.0'
          env:
            - name: server_addr
              value: 123.57.3.122
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          resources:
            requests:
              cpu: 500m
              memory: '100Mi'
            limits:
              cpu: 500m
              memory: '100Mi'
    metadata:
      labels:
        dce.daocloud.io/component: alpine-ovn
        dce.daocloud.io/app: crossx-ovn
      name: alpine-ovn
  selector:
    matchLabels:
      dce.daocloud.io/component: alpine-ovn
---
kind: Service
apiVersion: v1
metadata:
  name: alpine-ovn
  labels:
    dce.daocloud.io/app: crossx-ovn
  namespace: dev-env
  annotations: {}
spec:
  selector:
    dce.daocloud.io/component: alpine-ovn
    dce.daocloud.io/app: crossx-ovn
  type: ClusterIP
  ports:
    - targetPort: 1194
      protocol: TCP
      port: 1194
      name: alpine-ovn-1194